---
# tasks file for ansible-role-create-account 
- name: "USER | Create {{ user }}"
  user:
    name: "{{ user }}"
    groups:
    - www-data
    shell: /bin/bash
- name: "USER | Create {{ sudoer }}"
  user:
    name: "{{ sudoer }}"
    groups:
    - sudo
    shell: /bin/bash
  